project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Lois Adler-Johnson"
    background: primary
    search: true
    left:
      - text: "About"
        href: index.qmd 
      - text: "Resume/CV"
        href: resume-cv.qmd
      - text: "Portfolio"
        href: posts.qmd
      - text: "Makes"
        href: makes.qmd
      - text: "Resources"
        href: resources.qmd
    right:
      - text: "{{< iconify mdi:linkedin >}}"
        href: https://www.linkedin.com/in/loisaj/
      - text: "{{< iconify mdi:github >}}"
        href: https://github.com/joislohnson
      - text: "{{< iconify simple-icons:googlescholar >}}"
        href: https://scholar.google.com/citations?hl=en&user=2ZLHHkEAAAAJ
      - text:  "{{< iconify ic:outline-email >}}"
        href: mailto:lois.c.johnson+site@gmail.com

format:
  html:
    theme: zephyr
    css: styles.css
    toc: false

editor: visual

