project:
  type: website

website:
  navbar:
    title: "Lois Adler-Johnson"
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd 
      - resume-cv.qmd
      - portfolio.qmd
      - resources.qmd

format:
  html:
    theme: litera
    css: bootstrap.css
    toc: true

editor: visual

