project:
  type: website

website:
  navbar:
    title: "Lois Adler-Johnson"
    background: primary
    search: true
    left:
      - text: "About"
        href: about.qmd 
      - text: "Resume/CV"
        href: resume-cv.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Resources"
        href: resources.qmd

format:
  html:
    theme: litera
    css: bootstrap.css
    toc: false

editor: visual

